platform :ios, '11.0'
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'Example' do
  pod 'FaceppSwift', :path => '../'
  pod 'FaceppSwift/UIKit', :path => '../'
  pod 'FaceppSwift/WebKit', :path => '../'
  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.0.0'

end
